sonar.host.url=http://sonar-enterprise.uscis.dhs.gov:9000/
sonar.projectKey=gov.dhs.uscis.react-beacon
sonar.projectName=React-Beacon
sonar.login=jenkins
sonar.sourceEncoding=UTF-8
sonar.sources=libs/beacon
sonar.typescript.tsconfigPath=libs/beacon/tsconfig.json
sonar.typescript.lcov.reportPaths=coverage/libs/beacon/lcov.info
# Sonar with the sonarqube upgrade got a little greedy and we need to exclude some files from the scan and coverage
sonar.exclusions=libs/beacon/jest.config.js,libs/beacon/.storybook/**/*,libs/beacon/src/lib/stories/**/*,libs/beacon/src/lib/**/*.stories.tsx
sonar.coverage.exclusions=libs/beacon/jest.config.js,libs/beacon/.storybook/**/*,libs/beacon/src/lib/stories/**/*,libs/beacon/src/lib/**/*.spec.tsx,libs/beacon/src/lib/**/*.stories.tsx,libs/beacon/src/lib/**/*.spec.ts,libs/beacon/src/lib/logging/**/*,libs/beacon/src/lib/test-utils,libs/beacon/src/lib/icon/story-utils.ts